var GameConfig = {

	TILE_SIZE: 50,
	PLAYER_SPEED: 100,
	ENEMY_SPEED: 60,
	DEBOUNCE_DELAY: 200,
	TRANSITION_SPEED: 300,

	GOBLIN_CHASE_SPEED: 75,
	GOBLIN_VISION_DISTANCE: 200,
	GOBLIN_FOV: 50,
	GOBLIN_HINT_INTERVAL: 10,
	COIN_COUNT: 6

};
